### ISSUE TITLE
Add .htaccess example for individual document roots

### ISSUE THREAD

**Issue by Spacelord09** [Uberspace/manual#102]
Im using this snippet to use individual document roots for my subdomains can anyone add that to [the u7 manual](https://manual.uberspace.de/web-documentroot.html).

For example we have these domains added to our uberspace:
`uberspace.de`
`blog.uberspace.de`
`cloud.uberspace.de`

each of these subdomains has its own folder(Document root):
`uberspace.de` = `/var/www/virtual/$user/html/` (root domain)
`blog.uberspace.de` = `/var/www/virtual/$user/blog.uberspace.de/`
`cloud.uberspace.de` = `/var/www/virtual/$user/cloud.uberspace.de/`

To set the document roots accordently to the subdomains you need to add a .htacces in  `/var/www/virtual/$user/html/.htaccess` with the following content:

```
RewriteBase /

RewriteEngine on
RewriteCond %{HTTP_HOST} ^(.*)\.domain\.de
RewriteRule ^(.*)$ subdomains/%1/$1 [L,NC,QSA]
```

**Comment by luto** [comment]
Sorry, I don't quite follow. Requests for `blog.uberspace.de` already end up in `.../virtual/$user/blog.uberspace.de/` using the default configuration. The works for both domains, sub-domains, sub-sub-domain and so on.

What is the concrete problem the additional configuration solves?

**Comment by Spacelord09** [comment]
ok? for me not?

**Comment by luto** [comment]
interesting :grin: do you mind shooting us an email to hallo@uberspace.de with your username, so we can have a look?

Since this should already work, I'm closing this for now.

**Comment by Spacelord09** [comment]
@luto Mail is shot ;D

**Comment by luto** [comment]
Result of our mail conversation: works as expected.
