### ISSUE TITLE
fix typos

### ISSUE THREAD

**Issue by SalocinHB** [Uberspace/manual#118]
https://twitter.com/rumo_nintendo/status/1230147891462918144

 2 Typos gefunden  http://manual.uber.space/mail-filter.html autolern->autolearn, http://manual.uber.space/mail-domains.html framwork -> framework

**Comment by Spacelord09** [comment]
Why revert? ;D

**Comment by nichtmax** [comment]
We changed a lot with v7.4.1, it's just easier to fix later than to rebase 🙈
