### ISSUE TITLE
contradicting info about mailboxes

### ISSUE THREAD

**Issue by flauschzelle** [Uberspace/manual#122]
The manual currently says [this](https://manual.uberspace.de/mail-mailboxes.html#system-mailbox):

> You should only use the system mailbox for computer generated mails like status updates and such since **you can’t use it with your own domains** and no filtering is done.

But I am actually just using the system mailbox with my own domain (I haven't set up any mailboxes, just added the domain as described [here](https://manual.uberspace.de/mail-domains.html#setup).) and it works. So this is either outdated or was meant to say something else?

And the [dashboard](https://dashboard.uberspace.de/dashboard/mail) says this:

> You'll need virtual mailboxes in case you want to receive mail for additional addresses **separated** from your primary mail address, i.e. you get separate data for POP/IMAP. If you just want additional addresses that point to the **same** mailbox, it's easier to create simple forwardings (see above). 

So if I don't want to separate the system mails from the mails that I get at my own domain (as in: I use one account in my mail client for all mails on this uberspace), is there any reason why I should set up a separate mailbox anyway? 
In that case, the reason should be explained more clearly in the manual *and* the dashboard to avoid more confusion.

**Comment by nichtmax** [comment]
https://github.com/Uberspace/manual/commit/d8915c86f171144e59f1b6a095ad3a401f7dbecc
