### ISSUE TITLE
add glossary

### ISSUE THREAD

**Issue by nichtmax** [Uberspace/manual#133]
explain symlinks and how to use them. And whatever else comes to mind.

**Comment by luto** [comment]
I don't like "glossary". A glossary should explain what a symlink is, but shouldn't teach me how to use them:

> an alphabetical list of words relating to a specific subject, text, or dialect, with explanations; a brief dictionary.

This change gives us three areas:

* how to use uberspace? probably doesn't need a name, it's just "the manual".
* how does uberspace work behind the secenes? currently "background".
* how to use linux (and uberspace as side effect)? doesn't exist yet.

What do we name each of them?

**Comment by nichtmax** [comment]
We'll cover parts of this in the first day section.
