### ISSUE TITLE
HSTS (HTTP Strict Transport Security)

### ISSUE THREAD

**Issue by beerisgood** [Uberspace/manual#143]
It would be great if HSTS can be configured with recommend settings, as a change on user side isn't possible (at the moment):
`Strict-Transport-Security: max-age=63072000; includeSubDomains; preload`

https://hstspreload.org/
https://infosec.mozilla.org/guidelines/web_security#http-strict-transport-security

**Comment by luto** [comment]
We've got an internal issue about that and I went ahead and added your +1 to that. This issue tracker is about problems and extensions to the manual, not U7 itself. So I'll have to close this one.
