### ISSUE TITLE
first day: for U6 Users

### ISSUE THREAD

**Issue by luto** [Uberspace/manual#15]
Purpose of this page is providing a sense of feeling at home quickly. It's probably the first piece of documentation new users are reading after registering an account, so it should be really well-crafted. Probably first showing support options.

* What's the same (e.g. directory structure)?
* What's different (e.g. automatic HTTPS)?
* What doesn't work anymore, and why (e.g. wildcard domains)?

**Comment by noave** [comment]
ha didnt know that there already was an issue, , fixed by https://manual.uberspace.de/firstday-ubernauts/
