### ISSUE TITLE
changelog feed always updates every single item

### ISSUE THREAD

**Issue by SalocinHB** [Uberspace/manual#156]

**Comment by nichtmax** [comment]
I don't know the exact reason but with every release we completely replace the old version of the manual and the changelog is kind of hacky. 

Maybe there is a way to tell the feed that only the latest entry is new? @luto any idea?

**Comment by luto** [comment]
We now set `<updated>` for each entry. Please check again and reopen, if that's not enough.

**Comment by ezzra** [comment]
> We now set `<updated>` for each entry.

I first wondered how this could help but I see you set it so the same old date, should work that way :)

_by the way, just for the error finding, in the old feed all `<updated>` where set to the same date and seconds, but not microseconds, so it looks like it is set for each item seperately and not once and reused that value for each item._
