### ISSUE TITLE
extend manual for mail setup for custom domains on uberspace7

### ISSUE THREAD

**Issue by lockejan** [Uberspace/manual#160]
Hi,
the documentation seems to lack crucial informations on how to properly setup custom mailboxes for a given domain.
All blogs I could find on that topic are related to uberspace6.
The u7-cli isn't compatible with the u6-cli examples one can find on the net.
Like, how to work with namespaces on u7 or what could go wrong during setup? 
I would contribute some text, but at first I need to make it work.

**Comment by nichtmax** [comment]
> Like, how to work with namespaces on u7 or what could go wrong during setup?

There are no mail spaces with U7. We simplified the setup, every mailbox works with every domain.

**Comment by lockejan** [comment]
Hmm, ok. Thanks for the link.
However I've got the feeling that some crucial information is still missing because after doing the setup test-mails are still failing with a 550. 
I've updated my MX-Record yesterday. 
`dig my.domain MX +short` results in...
`10 arche.uberspace.de.my.domain`.
I'm not sure if this is correct, but I can't figure it out with the docs...

**Comment by nichtmax** [comment]
Please [get in touch with our support](mailto:hallo@uberspace.de), we'll figure out what's missing ☺️
