### ISSUE TITLE
think about section about contractual stuff

### ISSUE THREAD

**Issue by nichtmax** [Uberspace/manual#162]
- when do we delete data when an account is unpayed?
- when do we disable accounts?
- ...

**Comment by mk-pmb** [comment]
More general,
* What happens when a payment is due and the account balance is insufficient?
* If balance is too low for the selected tier but would suffice for the next lower tier, will it downgrade automatically? Just that time or permanently until it is upgraded again?

**Comment by nichtmax** [comment]
@mk-pmb We don't have tiers 😅 

But I get your point. We'll keep your questions in mind, thanks!

**Comment by Spacelord09** [comment]
@nichtmax
I think @mk-pmb ment with "the selected tier" the configured price.

For example elisa has 5€ on his account left and his price is 6€.
Is the price then automatically set to "the lower tier" or 5€?

**Comment by mk-pmb** [comment]
Reading the "Pricing" page again, I see that you call it "reference values" there. When I first looked at it, I only skimmed the headlines and thus thought those recommendations were tiers.

**Comment by noave** [comment]
because there is already https://manual.uberspace.de/billing-general/#what-happens-when-you-stop-paying this issue is imho fixed and replaced by https://github.com/Uberspace/manual/issues/340
