### ISSUE TITLE
better document identity of ssh and smtp password

### ISSUE THREAD

**Issue by cknoll** [Uberspace/manual#167]
I am referring to https://manual.uberspace.de/mail-access.html#smtp

Despite using several uberspaces for serveral years now it was not known to me until yesterday that the smtp password is identical to the ssh password. Allthoough the existence of webmail is quite hidden (see #166), i knew that somehow. But I expected the pw to be the same as the one for the webfrontend.

I suggest
- In every password row of the tables for [imap](https://manual.uberspace.de/mail-access.html#imap), [pop](https://manual.uberspace.de/mail-access.html#pop) and [smtp](smtp),  add a short link to the warning at the top of the page.
- There should be some hint on <https://dashboard.uberspace.de/dashboard/authentication> that the two passwords are identical.
  - Simple solution: replace `SSH-Zugang` by `Webmail und SSH-Zugang` (currently dont know the exact wording of the english version)
  - Maybe not the most elegant solution.
- There should be a link to <https://manual.uberspace.de/mail-access.html> on the login page of <https://webmail.uberspace.de/>, next/below to "mobile Version".

**Comment by noave** [comment]
sorry for the very late response

1. I would not like to add a link for this special case to all password rows, but I made it more clear with a headline and formatting at the top.
2./3. I will open internal issues for these ideas, thanks!

**Comment by noave** [comment]
reopening to wait for #339
