### ISSUE TITLE
"Accessing your emails" and multiple mail boxes

### ISSUE THREAD

**Issue by The-Compiler** [Uberspace/manual#181]
The "Accessing your emails" page only says this for IMAP and SMTP:

> email: Your email address, including the domain
> Password: Your password for the email address

It took me a while to find out that I should use the user/password added via `uberspace mail user add` for IMAP (in my case, `compiler@compiler.uber.space`), but the uberspace account itself (`compiler@uber.space`) and its password for SMTP.

IMHO, this should be explained better, "your email addess" and "your password for the email address" is quite ambiguous.

**Comment by SalocinHB** [comment]
You don't need to use a different user/password combination for SMTP

**Comment by The-Compiler** [comment]
Hm, you're right. `smtp://compiler@compiler.uber.space@devico.uberspace.de:587/` and the password I set via `uberspace mail user add` works just fine. My bad, I guess I did some mistake when I tried before.
