### ISSUE TITLE
Tell users how to work with quota

### ISSUE THREAD

**Issue by jonmz** [Uberspace/manual#185]
While the output of `quota -gsl` tells a user how much storage he is using, the question most users have is "what data is all this". In our support, we explain users how to use `ncdu $HOME` and `ncdu /var/www/virtual/$USER` quite regularly, so we should put this into our manual.

While a tool like `uberspace tools quota list` could also be nice (internal issue 541), explaining a more general tool that may be useful on non-uberspace systems as well seems quite appropriate here.

**Comment by noave** [comment]
guess this is fixed by the PR, closing for now
