### ISSUE TITLE
Update "web security headers" example -- as it has become nonsense now

### ISSUE THREAD

**Issue by Sgt-Nukem** [Uberspace/manual#193]
The example in [**Replacing security headers**](https://manual.uberspace.de/web-headers.html#headers):
```
[isabell@philae ~]$ uberspace web header set /blog Strict-Transport-Security "max-age=31536000"
Set header "Strict-Transport-Security: max-age=31536000" for /blog
```

is a no-op now, as 31536000 is the default nowadays. This example should be adjusted to avoid confusion for rookies.

Someone should re-read the whole page for similar issues, too.

**Comment by luto** [comment]
right! thank you :)
