### ISSUE TITLE
Add SSH config to docs

### ISSUE THREAD

**Issue by Ryuno-Ki** [Uberspace/manual#216]
Today, I was running through the migration from U6 to U7 (yes, I know, about time).
Therefore, I uploaded a new SSH key of ED25519 type.

While going through [the docs](https://manual.uberspace.de/basics-ssh.html#ssh-working-with-keys) I wondered, whether adding a [SSH Config file](https://wiki.qt.io/Setting_up_Gerrit#Local_Setup) might make sense as well.

The file to be edit would be https://github.com/Uberspace/manual/blob/f09872b5d07467726aa5f28b62c5ea943dd6c2c0/source/basics-ssh.rst#working-with-keys

**Comment by noave** [comment]
A ssh config file makes sense in general, yes, but because we want to focus on the *basic ssh* settings this might bring more confusion. We could think about mentioning it with a link to an external description how to use it.

**Comment by noave** [comment]
because you gave thumbs up I would close this issue now :)

**Comment by Ryuno-Ki** [comment]
Fine with me.
