### ISSUE TITLE
IMAP folder naming

### ISSUE THREAD

**Issue by sunflower-seed** [Uberspace/manual#225]
It might be helpful to add which language the standard IMAP folder names have (INBOX, Drafts, Sent).

As you already mention the naming of the Spam folder you complement this with the full folder set names.

The reason for this suggestion is that not all mail clients automatically detect the correct folder names. Seen this issue in K9-Mail on a German Android phone.

(I'm quite not sure if the folder names have been in German in U6 or Roundcube created some)

**Comment by luto** [comment]
This is a known U7 bug because we currently do not set the RFC 6154 "SPECIAL-USE" flags, which mail clients use to detect which folder is trash, sent, spam, etc. We'll fix this in U7 so it just works magically instead of documenting the brokenness.
