### ISSUE TITLE
Docs update for idn conversion / punycode

### ISSUE THREAD

**Issue by Maddosaurus** [Uberspace/manual#238]
Hey team!

Today I wanted to convert a domain to punycode to add it to my uberspace.  
Accoding to the [manual for web domains](https://manual.uberspace.de/web-domains/#setup), the usage of `idn` is recommended for this. At least on Fenrir, this fails with
```
[user@fenrir ~]$ idn überspace.de
idn: could not convert from ANSI_X3.4-1968 to UTF-8
```
Checking the [idn troubleshooting info](https://www.gnu.org/software/libidn/manual/html_node_db/x1292.html) it seems this might be due to a wrong LANG variable. Converting German Umlauts seems to only work when LANG is set to *de_DE*. As this might have unwanted side effects, I would propose to update the documentation to something along the lines of:
```
[isabell@stardust ~] $ LANG=de_DE.utf8 idn überspace.de
```
This would call `idn` with a temporary LANG setting, therefore getting the wanted result without a permanent change to the system / user environment.

Thanks everyone!

**Comment by luto** [comment]
It's the `.utf8` part that's important here. Your local terminal reports something else via SSH, causing the shell within your uberspace to be something-that's-not-utf8.

If the local terminal is utf8, this works fine:

```
[root@tuttle ~]# idn überspace.de
xn--berspace-55a.de
```
