### ISSUE TITLE
add info on trouble shooting the migration

### ISSUE THREAD

**Issue by pascoda** [Uberspace/manual#245]
on "Your first day… for Ubernauts from U6", explicitly mention the trouble shooting part of the uberspace2uberspace wiki article, or add that information here (it IS U7-relevant info after all)

**Comment by noave** [comment]
sorry for the late response. Because the manual migration is no longer available and we automigrate the remaining U6 hosts the wiki article is very much outdated. If you have any specific problems that should still be mentioned on the firstday for ubernauts from u6 page you can reopen the issue
