### ISSUE TITLE
how to use managed sieve

### ISSUE THREAD

**Issue by nichtmax** [Uberspace/manual#247]
add examples
 - forward mail
 - filter mail
 - sort mail into folders
 - ...

**Comment by Starkstromkonsument** [comment]
I tried to set it up for one of my mailboxes by using the Thunderbird Sieve Plugin. It puts the *.sieve config files into the directory `<maildir>/sieve` (e.g. `$HOME/users/<mailbox>/sieve`). It is not processed though. Are any further changes needed, e.g. to the .qmail-file (I have the default one with `|/usr/bin/vdeliver` in place)?

**Comment by nichtmax** [comment]
@Starkstromkonsument `|/usr/bin/vdeliver` does not work. You'll need to enable [our Spamfilter](https://manual.uberspace.de/mail-spam/).

**Comment by nichtmax** [comment]
merged #275
