### ISSUE TITLE
use plain text newlines instead of `<br>` for changelog in atom feed

### ISSUE THREAD

**Issue by raffaelj** [Uberspace/manual#266]
I subscribed to the changelog for a while and everytime, I read a new update, I have to open a browser to read the changes with proper line breaks. Otherwise, it is unreadable if there are more than a few changes.

**Screenshot:**

![uberspace_changelog_Screenshot_20210125_211156](https://user-images.githubusercontent.com/13042193/105760428-13dade80-5f52-11eb-9951-13fc978bf957.png)

**System:**

Feed reader: Akkregator
Feed url: https://manual.uberspace.de/en/changelog.atom
OS: OpenSUSE Tumbleweed/KDE Plasma5

**Comment by luto** [comment]
@raffaelj does this one work? https://deploy-preview-267--manual-uberspace-de.netlify.app/changelog.atom

**Comment by raffaelj** [comment]
@luto Now it doesn't display the content anymore.

I had a quick look at a different feed with working html and it looks like the html_entities encoded content was correct, but the `<content>` needs a `type="html"` to work correctly.

Working feed:
https://github.com/shiftkey/desktop/releases.atom

```xml
<content type="html">&lt;h2&gt;Additions&lt;/h2&gt;...</content>
```

Current feed:

```xml
<content>Added&lt;br&gt;-----&lt;br&gt;
```

preview feed:

```xml
<content type="CDATA"><![CDATA[Added<br>-----<br>...]]></content>
```

**Comment by luto** [comment]
@raffaelj how about now (same URL)? :sweat_smile:

**Comment by raffaelj** [comment]
@luto Much better :-)

For some reason, the first linebreak isn't recognized (see screenshot). Not sure, if this is a problem of Akkregator or if the xml isn't valid enough.

![uberspace_changelog_Screenshot_20210126_101157](https://user-images.githubusercontent.com/13042193/105825630-1aa03a80-5fc0-11eb-9a10-bf59371014b1.png)

I also tested the new feed with Thunderbird on an old Windows 7 laptop and the first linebreak is displayed correctly. The old feed also didn't have any linebreak at all.

So... I would go with "good enough". But it doesn't feel correct ;-)

I think, the feed should either be
* of `type="text"` (default if type is omited) and contain the raw text with `\r\n` instead of any `<br>` tags or
* of `type="html"` with the full markdown to html converted text.

**Comment by luto** [comment]
how about now? (I could really just get myself a feed reader, hm? but I hope this is the last one)

**Comment by raffaelj** [comment]
> I could really just get myself a feed reader, hm?

:D

Now Thunderbird (Windows) doesn't have line breaks anymore and Akkregator (Linux) still doesn't recognize the first line break (like on the last screenshot). Weird...

So the last one with `type="html"` and encoded br tags was better.

And finally I found the source for the feed in `conf.py`. Probably a better solution than my [last attempt of building an rss feed][1] with jeykyll in liquid with a lot of filter magic...

Interesting topic, but cross feed reader development is a pain :-(

[1]: https://github.com/raffaelj/raffael.one/blob/gh-pages/feed.xml

**Comment by luto** [comment]
Thanks!

**Comment by raffaelj** [comment]
Thanks for the fix.
