### ISSUE TITLE
add docu for .maillimit

### ISSUE THREAD

**Issue by noave** [Uberspace/manual#290]
the ratelimit is documented by a readme in the `.maillimit` folder but we might want to document it in the manual too

**Comment by ilakast** [comment]
Hi - can I ask where is the `.maillimit` folder located? Thanks

**Comment by noave** [comment]
at `~/.maillimit` but it will only be created if you use sendmail

**Comment by web-pat** [comment]
What about other files that are created in the .maillimit folder, such as mail.sdKKMslkjdf. Does this indicate a limit violation?
