### ISSUE TITLE
Sieve - ereject capabilities?

### ISSUE THREAD

**Issue by FrederikLauber** [Uberspace/manual#297]
Hi,

I am investigating a switch from my previous .qmail config to the new sieve filtering system.
One thing that seems to miss is to reject emails during a SMTP transaction. 
The normal reject works but that creates a bounce email instead of the perceived sender instead of refusing accepting the email to begin with.

Will this be implemented in the future or is rejecting emails on the SMTP level only available via qmail files?
Cheers,

PS:
Below is the rfc for ereject
https://tools.ietf.org/html/rfc5429

**Comment by jonmz** [comment]
Hi Frederik,

the SMTP server only knows which addresses _exist_ and which addresses do not exist (and thus are rejected on the SMTP level).

Sieve scripts are called from the local delivery agent (dovecot-lda) _after_ the SMTP session is already completed, so to my knowledge it will be impossible to reject anything on the SMTP level at that stage. From my understanding that would need a tight integration with the SMTP server which is not possible with our current chain of tools.

Just to be sure: Even using the traditional .qmail files, there is no possibility to make the SMTP server reject mails based on your own criteria. Mails are only rejected if they trigger our spam filter or if the destination address really doesn't exist.

**Comment by FrederikLauber** [comment]
True that you could not reject the mails based on content but you could do that based on the address they were sent to. This is now not possible anymore as far as I understand it as you can only have one catch-all mailbox for all possible addresses and not partially matching ones.
I.E. in the pat you could have .qmail-mailinglist-default and then dynamically have mailinglist-test@foo.bar while any other address was rejected. Once you start using mailboxes, this is not possible anymore, or am I wrong here?

Anyway, ereject would be an amazing feature but I get that you cannot implement it. Gona stay with my system mailbox + .qmail files then.

**Comment by jonmz** [comment]
I'm relatively sure you're wrong here, sorry. U6 or U7, Sieve or no Sieve: In any case it's the .qmail files that decide which addresses are accepted. The -default extension of .qmail files is treated the same as in the past: Having a .qmail-mailinglist-default would accept all addresses mailinglist-<xyz>@foo.bar while other addresses are rejected, both under U6 and under U7. Unless you have a catchall address, sure.

If you feel some trouble here, please contact our support team at hallo@uberspace.de as this behaviour should be unchanged from the past. Regard ereject (this issue), I fear there is nothing to be done here. Even the Dovecot Pidgeonhole Sieve implementation itself openly tells that ereject is currently mapped to reject, so it's not a matter of configuration but of the Sieve implementation itself not supporting the functionality you are looking for.

**Comment by FrederikLauber** [comment]
I think you misunderstood. In U6, using the system mail box and managing addresses per qmail files, accepting and rejecting was possible based on the mail address jsut as you described. Once accepted, you could not ereject the mails, absolutely true.
From what I understand, Sieve is to replace the qmail files in the future (as noted for example here: https://manual.uberspace.de/en/mail-forwarding/?highlight=qmail). But then you can only use mailboxes to reject and accept mails and hence the issue I described arises as you cannot have default mail boxes, only one catch all. Adding ereject to Sieve would get rid of this issue but I can see that this is not possible due to the setup.

**Comment by jonmz** [comment]
Ah, now I see where your thoughts and worries are going...

Well. While we are _shifting_ more functionality to Sieve as it is a more standard method to do things, .qmail files are very unlikely to go away anytime soon, as this would break existing mail setups and user-installed software like ezmlm-idx which rely on the -default mechanism of .qmail files.

In most cases, .qmail files are used to implement mail forwards, and we want to integrate this in a cleaner and more comfortable and controllable way than educating users to create .qmail files. "We no longer provide support" means exactly this: Our support team will no longer debug problems of user-created .qmail files that effectively work around our mail system. It does _not_ mean that their functionality will go away.
