### ISSUE TITLE
Missing access rights to read the current nginx config

### ISSUE THREAD

**Issue by schlenger** [Uberspace/manual#311]
Like specified in https://github.com/Uberspace/manual/blob/main/source/background-http-stack.rst the command `[root@stardust ~]# cat /etc/nginx/user.d/marie.conf` is not working (of course with the updated username) due to the restricted access rights.

This should be eiter resolved in the docs or the right administration. In the second case it would be helpful for debugging purposes to at least read the current configuration in some kind of way.

**Comment by noave** [comment]
sorry for the late response and thanks for the info, we have an open issue for fixing this in U7, it should be taken care for within the next releases (no guarantee :wink: )
