### ISSUE TITLE
Improve documentation on using Sieve

### ISSUE THREAD

**Issue by PeterNerlich** [Uberspace/manual#317]
`source/mail-filters.rst` tells me what Sieve can do and implies I have to write scripts to define the desired behaviour. Maybe I am a dull reader, but it took me until writing this line to realize I don't save the scripts somewhere as files, but have to use a tool speaking the control protocol: The section "Manage Sieve" opens with "Many E-mail clients support..." and I'm thinking "okay I just want to save the rules script to disk".

I suggest writing a sentence like "To create and manage Sieve scripts, you have to use a tool speaking the control protocol..." to make it less easy to just glance over.

**Comment by Bibabidu** [comment]
I'm highjacking this issue to mention another potential improvement within the documentation. I'm not sure if the preferred way would have been to open a separate issue, if so please let me know and I'll do that. 

Yesterday, I've spent some time setting up my emails and playing around with Sieve. I've added the default example from the manual and all my emails ended in the "Spam" folder. After checking the headers of the emails, and spending some time googling, I've noticed that Sieve isn't able to deal with negative spam scores. I've found a working solution [here](https://www.cc-community.net/threads/sieve-filterproblem-bei-negativem-x-spam-score-wert.109959/).

I would suggest adding this line `not header :matches "x-rspamd-score" "-*"` to the example, and making sure that emails with negative spam score don't get sorted away (at least in my case they were all legit. 
```
if allof
    (
      header :value "ge" :comparator "i;ascii-numeric" "X-Rspamd-Score" "4",
      not header :matches "x-rspamd-score" "-*"
    )
{
    fileinto :flags ["\\Seen"] "Spam";
    stop;
}
```

In case anybody sees a problem with this solution, or has a reason why this is best practice, please let me know!

**Comment by noave** [comment]
@Bibabidu yes, pls open a separate issue

**Comment by noave** [comment]
@PeterNerlich I used your text snippet in the pull request #333
