### ISSUE TITLE
Explain in manual or lab how to use autorespond for mails

### ISSUE THREAD

**Issue by Thorgrimson** [Uberspace/manual#371]
Found this on the web: https://gist.github.com/tpraxl/6d5be3527490fb51f33ae5eafe747714
Maybe one could add it in manual or lab (not shure where it should be)

**Comment by nichtmax** [comment]
You can configure an autoresponder with [sieve](https://manual.uberspace.de/mail-filters/). You _could_ use maildrop scripts but there's a reason we don't document maildrop: That's legacy from Uberspace 6 and we deprecated it with Uberspace 7.
