### ISSUE TITLE
remove PuTTY from SSH article

### ISSUE THREAD

**Issue by nichtmax** [Uberspace/manual#377]
Windows 10 and 11 [bring their own ssh client](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse), Windows 7 is EOL.

Remove when Windows 8 is EOL

**Comment by SalocinHB** [comment]
> Windows 8.1 reached the end of Mainstream Support on January 9, 2018, and will reach end of Extended Support on January 10, 2023.

https://docs.microsoft.com/en-us/lifecycle/faq/windows#what-is-the-lifecycle-policy-for-windows-8-1-

I suggest to move PuTTY to a separate article and only link it from the SSH article, then remove it on or after 10 January 2023.
