### ISSUE TITLE
document domain rules

### ISSUE THREAD

**Issue by luto** [Uberspace/manual#4]
We should document our _"domain rules"_. 

Current state on U7: After a user successfully registered a domain (with `uberspace <web|mail> domain add …`) neither the domain nor any sub domain of it can can be registered by any other user _on that host_ (regardless of the type, i.e. _web_ / _mail_). This is in contrast to U6, where different users can have access to the same domain, if different types (_web_ / _mail_) are used.

**Comment by noave** [comment]
outdated, already documented now (with workaround for subdomains)
