### ISSUE TITLE
Update the list of enabled php modules/extensions

### ISSUE THREAD

**Issue by Emaro** [Uberspace/manual#426]
I was about to install the [Kriby CMS](https://getkirby.com/), which lists four required php modules: `mbstring`, `curl`, `ctype` and `gd`. In the [PHP manual](https://manual.uberspace.de/lang-php/) `curl` and `ctype` are not listed. First I was worried, but then I checked the output of `phpinfo();` (using PHP 8.0). There, it says, that all four required modules are enabled.

I don't know if only the two modules I mentioned are missing, but I suggest that you update the provided PHP modules/extensions in the documentation.

**Comment by noave** [comment]
I updated the list: https://github.com/Uberspace/manual/pull/435
