### ISSUE TITLE
add docu on version EOL/deprecation

### ISSUE THREAD

**Issue by pascoda** [Uberspace/manual#446]
currently, there is only information on official EOL dates for e.g. PHP.
more information would be good so users know how long they can take to upgrade their things.

what we currently do:
* deprecate the EOL version on EOL date (i.e. users cannot select the version any more, but it still runs), and 
* remove the EOL version with the next release (about 1-2 months later; i.e. everyone who had selected it will be automagically upgraded to the next higher version).

**Comment by noave** [comment]
meanwhile we added explanatory notes to the version pages 

![image](https://github.com/Uberspace/manual/assets/70973333/a19be8a4-7432-4d24-9c38-6e832db9bbbf)
