### ISSUE TITLE
add notice that Gmail will reject mails without SPF and/or DKIM

### ISSUE THREAD

**Issue by SalocinHB** [Uberspace/manual#472]
> Important: Starting November 2022, new senders who send email to personal Gmail accounts must set up either SPF or DKIM. Google performs random checks on new sender messages to personal Gmail accounts to verify they’re authenticated. Messages without at least one of these authentication methods will be rejected or marked as spam. This requirement doesn’t apply to you if you’re an existing sender. However, we recommend you always set up SPF and DKIM to protect your organization’s email and to support future authentication requirements.

https://support.google.com/mail/answer/81126#authentication

**Comment by noave** [comment]
we added a notice here some time before: 
https://manual.uberspace.de/mail-domains/#spf-record

(did not know about this issue, closing here for now)

if you have specific support problems with your email, contact us at 
***@***.***
