### ISSUE TITLE
mysql: Change mtop to mytop

### ISSUE THREAD

**Issue by MaxValue** [Uberspace/manual#482]
There seems to be a typo in this manual:

At [this heading](https://manual.uberspace.de/database-mysql/#monitoring-and-analysing-sql-queries) there is the mention of a tool called mtop which does not exist. I guess it was meant to say mytop?

Relevant file: [/source/database-mysql.rst](/Uberspace/manual/blob/4118dc01f3372de49a0eb5363576363ddcff69a5/source/database-mysql.rst#monitoring-and-analysing-sql-queries)

**Comment by noave** [comment]
there is a tool named `mtop` that can be used in the  way like described in the manual, but with the updated mariadb came also `mytop` which seems to be better suited for using (no additional configuration needed), we already had the idea of replacing it in the manual. keeping this as a issues open for that suggestion :-)

**Comment by noave** [comment]
mytop is now already documented and replaced mtop
