### ISSUE TITLE
Replace Redis with compatible option (Valkey, Redict, etc)

### ISSUE THREAD

**Issue by filipesmedeiros** [Uberspace/manual#543]
Due to https://github.com/redis/redis/pull/13157, the FLOSS (among others) community is switching off of Redis en-mass, it seems.

https://github.com/valkey-io/valkey seems to be the new go-to, although https://codeberg.org/redict/redict also has a nice community behind it, I think.

Would we be interested in replacing Redis?

**Comment by SalocinHB** [comment]
> Would we be interested in replacing Redis?

Sure, but this repo is not meant for Uberspace feature requests.
