### ISSUE TITLE
document golang

### ISSUE THREAD

**Issue by luto** [Uberspace/manual#65]
Add a new language article for golang:

* only the newest version
* explain GOPATH a little, link to further docs

Merge only after v7.3.0.

**Comment by nichtmax** [comment]
@luto When we do it like [in the lab](https://lab.uberspace.de/guide_go.html#setup-environment-variables) it would be the first time we advise users to fiddle around with the `~/.bashrc`. Are we sure we don't want to setup this for every account by ourselves?

**Comment by luto** [comment]
@nichtmax The lab fiddles with `~/.bashrc` to add go to the `$PATH`. In the next U7 version will already be part of the default `$PATH`, so that's not necessary. What are you referring to?

[`$GOPATH`](https://github.com/golang/go/wiki/GOPATH) is separate from `$PATH` and used for dependency resolution and the current project path.

**Comment by nichtmax** [comment]
[Main article](https://manual.uberspace.de/lang-golang.html) is merged now.

To do:
- [ ] explain GOPATH a little
- [ ] link to further docs

**Comment by luto** [comment]
After reading up on GOPATH, explaining it in detail didn't seem necessary to explain it in detail anymore, which is why I skipped it. It's not needed in normal operation. If a concrete need arises, anyone can feel free to open a specific issue.
