### ISSUE TITLE
document java

### ISSUE THREAD

**Issue by luto** [Uberspace/manual#66]
We install java on U7 hosts, so document that.

**Comment by Sgt-Nukem** [comment]
This!

I read something about "Java is updated to version xy" in the changelog lately and it blew my mind. I remember an elaborate explanation of why Java is unwelcome (resource hog, etc.).

P.S.: Some weeks ago a friend asked if I know any VPS where he could play around with some Spring Boot -- as there are high-priced enterprise solutions out there, only. I said I know a (uber)cool space - but Java is a no-go, unfortunately. 😐

**Comment by Sgt-Nukem** [comment]
There should also be some explanation on WHAT can be done and HOW - for the regular J2EE / EJB programmer that is used to his JBoss / Tomcat application servers.

Can I run Spring Boot? Can I serve Servlets? etc.

**Comment by luto** [comment]
The manual only documents what is available, how updates are handled and changes to the tool, that are very specific to uberspace. All of that is available on https://manual.uberspace.de/lang-java, so this issue is done. Documenting how to install specific tools on top of that is [lab.uberspace.de](lab.uberspace.de)'s job. 

> for the regular J2EE / EJB programmer that is used to his JBoss / Tomcat application servers.
> Can I run Spring Boot? Can I serve Servlets? etc.

Most probably! However, documentation for this should live in our [lab](https://lab.uberspace.de/) ([github](https://github.com/Uberspace/lab/)) not in this repo. Feel free to open an issue there about the individual topics: jboss, tomcat, spring, servlets,.. :)
